from __future__ import annotations


# Parameters accepted by physics component object types.
# These names map directly to constructor kwargs in components/physics/*.py.
PHYSICS_OBJECT_PARAM_SPECS: dict[str, tuple[str, ...]] = {
    # Mechanics
    "InclinedPlaneGroup": (
        "angle",
        "length",
        "block_width",
        "block_height",
        "show_forces",
        "show_angle",
    ),
    "Wall": ("length", "angle", "hatch_spacing", "hatch_length", "color", "stroke_width"),
    "InclinedPlane": (
        "angle",
        "length",
        "color",
        "stroke_width",
        "fill_color",
        "fill_opacity",
        "show_angle",
    ),
    "Block": ("width", "height", "label", "label_color", "color", "stroke_width"),
    "Cart": ("width", "height", "wheel_radius", "color", "stroke_width"),
    "Weight": ("width", "height", "hook_radius", "color", "stroke_width"),
    "Pulley": ("radius", "rod_angle", "color", "stroke_width"),
    "FixedPulley": ("radius", "rod_length", "color", "stroke_width"),
    "MovablePulley": ("radius", "hook_length", "color", "stroke_width"),
    "Rope": ("length", "angle", "color", "stroke_width"),
    "Spring": ("length", "height", "num_coils", "end_length", "color", "stroke_width"),
    "Rod": ("length", "thickness", "color", "stroke_width"),
    "Hinge": ("radius", "color", "stroke_width"),
    "CircularGroove": ("radius", "groove_width", "color", "stroke_width"),
    "SemicircleGroove": ("radius", "groove_width", "color", "stroke_width"),
    "QuarterCircleGroove": ("radius", "groove_width", "corner", "color", "stroke_width"),
    "SemicircleCart": ("height", "wheel_radius", "color", "stroke_width"),
    "QuarterCart": ("side_length", "wheel_radius", "color", "stroke_width"),
    "SpringScale": ("width", "height", "reading", "color", "stroke_width"),
    # Electricity
    "Resistor": ("width", "height", "lead_length", "color", "stroke_width"),
    "Battery": ("width", "height_long", "height_short", "color", "stroke_width", "show_labels"),
    "Bulb": ("radius", "color", "stroke_width", "fill_color", "fill_opacity"),
    "Switch": ("width", "height", "color", "stroke_width"),
    "Capacitor": ("width", "height", "color", "stroke_width"),
    # Electromagnetism
    "EMBattery": (
        "height",
        "ratio",
        "plate_spacing",
        "wire_length",
        "is_positive_left",
        "color",
        "stroke_width",
    ),
    "EMSwitch": ("wire_length", "switch_length", "is_closed", "open_angle", "color", "stroke_width"),
    "Ammeter": ("radius", "wire_length", "label_scale", "color", "stroke_width"),
    "Voltmeter": ("radius", "wire_length", "label_scale", "color", "stroke_width"),
    "LightBulb": ("radius", "wire_length", "stroke_width", "color"),
    "EMCapacitor": ("height", "plate_spacing", "wire_length", "color", "stroke_width"),
    "Rheostat": (
        "body_width",
        "body_height",
        "handle_height",
        "alpha",
        "wire_length",
        "terminal_radius",
        "color",
        "stroke_width",
    ),
    "Potentiometer": (
        "body_width",
        "body_height",
        "wire_length",
        "arrow_scale",
        "arrow_angle",
        "color",
        "stroke_width",
    ),
    "Inductor": ("num_loops", "radius", "wire_length", "color", "stroke_width"),
    "LED": ("side_length", "wire_length", "arrow_size", "arrow_offset", "color", "stroke_width"),
}
